### ISSUE TITLE
Typos in 05.Basic_Concepts_IV.pdf

### ISSUE THREAD

**Issue by kimsoohwan** [federico-busato/Modern-CPP-Programming#10]
Hi Federico,

Thanks you very much for sharing your slides.
I found some typos in 05.Basic_Concepts_IV.pdf.

1. Page 5
The comment "// linking error "f" ist not defined" in the last line should be "// linking error "g" is not defined"

2. Page 32
First, I think "std::is_is_arithmetic<T>" should be "std::is_arithmetic<T>". "is_is" must be a typo.
Second, I'm not an expert on the "requires" keyword, but should it be "std::is_arithmetic_v<T>"?

Hope this helpful.
Thanks again.

Kind regards,
Soohwan

**Comment by federico-busato** [comment]
Hi @kimsoohwan, thanks a lot for reporting the typos. They are not easy to catch. You read the slides carefully 🙂. 
Just fixed. I will upload a new version soon.

**Comment by kimsoohwan** [comment]
Hi Federico,

Hope you're doing well.

I wanted to drop you a quick note to say how much I appreciate the C++ slides you shared online. Honestly, they're the best ones I've come across so far. Your way of explaining concepts and the detailed examples for common mistakes are incredibly helpful.

I'm actually thinking of using your slides for my C++ class at the university. Would it be alright with you? 
I'll not modify anything but make sure to give you full credit, of course.

Thanks a bunch for sharing your fantastic resources!

Best regards,
Soohwan

**Comment by federico-busato** [comment]
Thank you so much for your kind words! Knowing that other people find the course useful really helps me to stay motivated and improve the material.

I like to think of these slides as a "quick" guide to C++. I've also used them for myself since I can't able to remember all the concepts 😅

I have no problem if you want to use them. If you prefer, I can even remove my name from them. I touch C++ at university for 5yrs, but it is not easy. I started to get good results from students only in the last two years, moving the course to the master's degree.

**Comment by kimsoohwan** [comment]
Hi Federico,

Thanks you very much for letting me use your slides in my class. I really appreciate it. 
Please don't worry about changing your name or profile in the slides.
I intend to give you full credit as I mentioned.
Thanks heaps once again! 😊

Best regards,
Soohwan
