### ISSUE TITLE
 Permission to Use and Customize Course Material

### ISSUE THREAD

**Issue by amirkhaki** [federico-busato/Modern-CPP-Programming#31]
Hey federico,

Hope this finds you well! 👋 Your C++ course repo is a goldmine, seriously. 🚀 I'm in the process of putting together a university course on C++, and I'd love to use and tweak the material for my slides.

Your coverage of all the topics is spot-on, and I think it'll be a game-changer for my students.

I noticed there's no license file, so I wanted to check with you. I'll, of course, give full credit and add a link back to your repo.

If you're cool with it or have any conditions, just hit me up. Your work is top-notch, and I want to make sure I'm on the right side of things.

Cheers!

**Comment by federico-busato** [comment]
Hi @amirkhaki, thank you so much for your kind words! I'm very happy that the course is useful for you and your students!
 
yes, probably I need to add a license 😅. Anyway, I will send you the material by email.

**Comment by daniebera** [comment]
Hi Federico,

I hope this message finds you well! I saw that this issue was previously raised, and I’m in a similar situation. I’m currently preparing a university course involving C++ (half of the course) and recently discovered your repo. I must say, it’s an exceptional resource—very well-organized and thorough.

I’d like to ask for your permission to utilize and adapt your materials for my course slides, and I’d be happy to give you full credit, along with a reference link to the original repo.

Since there wasn’t a license specified, I just wanted to ensure I have your approval before proceeding. If there are any specific terms or conditions you'd prefer, please let me know!

Thanks again for the great work!

BW
Daniele

**Comment by federico-busato** [comment]
Hi Daniele,

I'm more than happy to know that the course can be useful to you and your students. I will send you the course source material by email soon. Anyway, please let me know if you have any feedback on how to improve the course or if you find any typos. Thank you very much.

**Comment by daniebera** [comment]
Hi Federico,

Thank you so much for your willingness to share the course material, I
truly appreciate it! I’ll keep an eye out for the email, and I’ll be sure
to share any feedback or suggestions for improvement as I go through the
content.

Thanks again for sharing your work; it will be super helpful for both me
and my students!

BW,
Daniele

Il giorno lun 16 set 2024 alle ore 08:30 Federico ***@***.***>
ha scritto:
